travis:
  secure:
    BINSTAR_TOKEN: DlSyCwSFpo4iCL86VitU8BTNKTkVKJgbuTV/iSDuY/cdyHaYLeVog4mcpmvjJR0964pLhQUXLS4X07/YNuksDlAUKiauzhhSDhFjwUSfbdYumBaVRokMsrdAzLEiDu1OOTYV/Sqwlao6C7LpnYe+JJqE6L/Tt8IuO0iVRhDwMcxLRc0tsIt5Mkm8cZ88EJIboHRWPf8zGVIQHlEQIU5i4ZBfpglJPY9cIp8WuPh1/2vJVuhM1K38QECF5SVyzozwtxT3GsGb0k6VfaMRqm8I4jAiF6OkJ4hqNEbHAN7qBet+MxhESeOVCYn9da0XGFgeG8UafVgRGS7yPKBdkauSoexJ0pAhTYUwu6gQM7edeMQishyQwS9Ktdvi4J0tvUyAwur+GwRPuJ8ekYAuZbZGymkcgMuqRRHpzkD6wPabrxYf5m8cymm8UfCWeW8585Xj91JOTsOFHp3WhMEQA+1No/aK3kuODsxizl0XDygkYP3oJaA1AfLCG9L0aAROn7DqBuzY/MuJP2S+i7Vy1CPHIUc2pckcimvjhqaeYa1vBYGRFt5AmvnnugTGzim0qzz/W0mB4FJro+YGHHyFUnSjByRg6yyYokZaNeAwvbXkcmW2dEDnCgfscQQXcYzQjof7jX3IMjK7KWbmxr2d1UXcuWTdO9waQ51iQJnzXwXBEb4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
