appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: GPOhzjEezkRWOKmQNTusIo3KZWt8QD8gri+/4TF3Gh+hwPvzoEoIWS5dbsHIP9+ieCQwonPu7QEYdeCBP23i2rChdvl7L9pMq521XIsGpaAy4I1UlVPMvrFdHW4F+1SnVqtXP/bwxUmTKqP0Cle93qHZvMmdUg0WqTaUJdXj93sHu/GgHou5EeCWxmOa0AfQv2FBAsjFybcMnibQ2jZHdh85TVzSThJD2IvDwMMJzpH65mS5G38shV4r80d7g15frXGlXpSuLj/toPCCBRhDHAyEMHwqe6YroB3qbNNwi9yjAAJwAx9Z25w+DGGt9ncTZuohXxvGNiDhPhz+6EDQlQrPplPEm7FzKPRL1gVsqzP1YWLkuO/6Jw+a+bJer7QFUXMq4daMwZJJadvaqW9IjNAo/pPGdCimuTSZQxBmb2u/qQ1lWQHtphvKH56GYxbt1lF5Xw8iLcnI9Br81VTNGv5lryVAzv6z/u9FpyvenHgHcoDybfMQtfvndXJZm3bUjDR/d9c8oyv6CLO4ufEPFCtGCe1efHFbj4n2c0niZvGx2NgP6wRdRfsi9TBRaJ17yKLstDfUOf901RxSqHmfGO3/yByqN1rGirdjZhtFS7FhUXAXYXb6xyzozX/aO5Px/YW2rTnKgMD59Xit/aj/3DSMIUELLISvbu3D4LspfcY=}
